# Generated by Django 6.0.3 on 2026-03-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contratos', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='contratos.contratos')),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'db_table': 'reclamos',
            },
        ),
    ]
