# Generated by Django 6.0.3 on 2026-03-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamos',
            old_name='contratos',
            new_name='contrato',
        ),
    ]
