# Generated by Django 6.0.3 on 2026-03-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_contratos_id_departamento_and_more'),
        ('reclamos', '0003_alter_reclamos_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamos',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='contratos.contratos'),
        ),
    ]
