### 1. Obtener todos los contratos
GET http://localhost:8000/api/contratos
Content-Type: application/json

### 2. Filtrar contratos por Inquilino (ID 2) y Status Activo
# Cambiado: id_inquilino -> inquilino_id
GET http://localhost:8000/api/contratos?inquilino_id=2&status=true
Content-Type: application/json

### 3. Crear Contrato - EXITOSO (Inquilino 2, Departamento 11)
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "inquilino_id": 2,
  "departamento_id": 11,
  "frecuencia_pago": "mensual",
  "monto": 2100000.00,
  "dia_pago": 10,
  "fecha_inicio": "2026-04-01",
  "fecha_fin": "2027-04-01",
  "status": true,
  "al_dia": true,
  "descripcion": "Contrato de alquiler residencial - Unidad 202"
}

### 4. Crear Contrato - ERROR (Fecha fin anterior a inicio)
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "inquilino_id": 2,
  "departamento_id": 11,
  "frecuencia_pago": "mensual",
  "monto": 1800000.00,
  "dia_pago": 5,
  "fecha_inicio": "2026-12-01",
  "fecha_fin": "2026-01-01"
}

### 5. Crear Contrato - ERROR (Frecuencia 'diario' no permitida)
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "inquilino_id": 2,
  "departamento_id": 1,
  "frecuencia_pago": "diario",
  "monto": 50000.00,
  "dia_pago": 1,
  "fecha_inicio": "2026-01-01",
  "fecha_fin": "2026-02-01"
}

### 6. Actualizar Contrato - EXITOSO (ID 1)
PUT http://localhost:8000/api/contratos/8
Content-Type: application/json

{
  "monto": 2250000.00,
  "al_dia": false,
  "descripcion": "Actualización de monto por expensas"
}

### 7. Actualizar Contrato - ERROR (Día de pago 32 es inválido)
PUT http://localhost:8000/api/contratos/1
Content-Type: application/json

{
  "dia_pago": 32
}

### 8. Eliminar Contrato - EXITOSO (ID 1)
DELETE http://localhost:8000/api/contratos/7
Content-Type: application/json

### 9. Eliminar Contrato - ERROR (ID 99999 no existe)
DELETE http://localhost:8000/api/contratos/99999
Content-Type: application/json

### 10. Crear contrato con departamento ocupado
POST http://localhost:8000/api/contratos
Content-Type: application/json

{
  "inquilino_id": 3,
  "departamento_id": 11,
  "frecuencia_pago": "mensual",
  "monto": 2500000.00,
  "dia_pago": 5,
  "fecha_inicio": "2026-05-01",
  "fecha_fin": "2027-05-01",
  "descripcion": "Intento de contrato en departamento ya ocupado"
}