class AppRoutes:
    DEUDAS = '/api/deudas'
    DEPARTAMENTOS = '/api/departamentos'
    EDIFICIOS = '/api/edificios'
    INQUILINOS = '/api/inquilinos'
    PAGOS = '/api/pagos'
    ABONOS = '/api/abonos'
    RECLAMOS = '/api/reclamos'
    CONTRATOS = '/api/contratos'
    LOGIN = '/api/auth/login'
    REGISTER = '/api/auth/register'
