# Generated by Django 6.0.3 on 2026-03-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contratos', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='contratos.contratos')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ayuda_dep', models.BooleanField(default=False)),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='finanzas.pagos')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'db_table': 'abonos',
            },
        ),
    ]
