# Generated by Django 6.0.3 on 2026-03-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_rename_contratos_pagos_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonos',
            old_name='pago',
            new_name='id_pago',
        ),
        migrations.RenameField(
            model_name='pagos',
            old_name='contrato',
            new_name='id_contrato',
        ),
    ]
