# Generated by Django 6.0.3 on 2026-03-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_remove_contratos_id_departamento_and_more'),
        ('finanzas', '0003_rename_pago_abonos_id_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonos',
            name='id_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='id_contrato',
        ),
        migrations.AddField(
            model_name='abonos',
            name='pago',
            field=models.ForeignKey(db_column='pago_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='finanzas.pagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagos',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='contratos.contratos'),
            preserve_default=False,
        ),
    ]
