# Generated by Django 6.0.3 on 2026-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('status', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('numero_identificion', models.CharField(max_length=60)),
                ('tipo_identificacion', models.CharField(choices=[('Cedula', 'cedula'), ('Pasaporte', 'pasaporte'), ('Ruc', 'ruc'), ('Licencia', 'licencia')], max_length=60)),
            ],
            options={
                'db_table': 'inquilinos',
            },
        ),
    ]
