# Generated by Django 6.0.3 on 2026-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquilinos',
            old_name='numero_identificion',
            new_name='numero_identificacion',
        ),
    ]
