# Generated by Django 6.0.3 on 2026-03-21 15:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0001_initial'),
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_pago', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')])),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.BooleanField(default=True)),
                ('dia_pago', models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('al_dia', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='edificios.departamentos')),
                ('inquilino', models.ForeignKey(db_column='id_inquilino', on_delete=django.db.models.deletion.CASCADE, to='inquilinos.inquilinos')),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
    ]
