# Generated by Django 6.0.3 on 2026-03-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('motivo', models.CharField(choices=[('Departamento', 'departamento'), ('Ande', 'ande')], max_length=20)),
                ('monto', models.IntegerField()),
                ('fecha_comienzo', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('contratos', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='contratos.contratos')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'db_table': 'deudas',
            },
        ),
    ]
