# Generated by Django 6.0.3 on 2026-03-23 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_deuda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deuda',
            old_name='contratos',
            new_name='contrato',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='dia_pago',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
