# Generated by Django 6.0.3 on 2026-03-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_rename_contratos_deuda_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='departamento',
            new_name='id_departamento',
        ),
        migrations.RenameField(
            model_name='contratos',
            old_name='inquilino',
            new_name='id_inquilino',
        ),
        migrations.RenameField(
            model_name='deuda',
            old_name='contrato',
            new_name='id_contrato',
        ),
    ]
