# Generated by Django 6.0.3 on 2026-03-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_rename_departamento_contratos_id_departamento_and_more'),
        ('edificios', '0004_remove_departamentos_id_edificio_and_more'),
        ('inquilinos', '0002_rename_numero_identificion_inquilinos_numero_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='id_departamento',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='id_inquilino',
        ),
        migrations.RemoveField(
            model_name='deuda',
            name='id_contrato',
        ),
        migrations.AddField(
            model_name='contratos',
            name='departamento',
            field=models.ForeignKey(db_column='departamento_id', default=12, on_delete=django.db.models.deletion.CASCADE, to='edificios.departamentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='inquilino',
            field=models.ForeignKey(db_column='inquilino_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.inquilinos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deuda',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='contratos.contratos'),
            preserve_default=False,
        ),
    ]
