# Generated by Django 6.0.3 on 2026-03-21 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'edificios',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_departamento', models.CharField(max_length=20)),
                ('piso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ocupado', models.BooleanField(default=False)),
                ('edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='edificios.edificios')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
    ]
