# Generated by Django 6.0.3 on 2026-03-22 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificios',
            name='nombre',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
