# Generated by Django 6.0.3 on 2026-03-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0002_alter_edificios_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentos',
            old_name='edificio',
            new_name='id_edificio',
        ),
    ]
