# Generated by Django 6.0.3 on 2026-03-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_rename_edificio_departamentos_id_edificio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='id_edificio',
        ),
        migrations.AddField(
            model_name='departamentos',
            name='edificio',
            field=models.ForeignKey(db_column='edificio_id', default=6, on_delete=django.db.models.deletion.CASCADE, to='edificios.edificios'),
            preserve_default=False,
        ),
    ]
